apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
spec:
  selector:
    kudo.dev/instance: {{ .Name }}
    version: green  
    component: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Params.port }}
      targetPort: {{ .Params.port }}
